### ISSUE TITLE
missing poscode

### ISSUE THREAD

**Issue by afandiazmi** [AsyrafHussin/npm-malaysia-postcodes#3]
75250 ni melaka, tapi takde dlm senarai, boleh update base on this tak? ni latest daripada  https://malaysiapostcode.com/download
[Malaysia_Postcode-latest.csv.zip](https://github.com/AsyrafHussin/npm-malaysia-postcodes/files/11141788/Malaysia_Postcode-latest.csv.zip)

atau boleh saya edit yg ni?

**Comment by AsyrafHussin** [comment]
Boleh tolong edit dan submit pull request x?

**Comment by AsyrafHussin** [comment]
I'm pleased to inform you that I recently updated the postcodes for Melaka, including the one you highlighted (75250), in our latest release (v1.4.0). If you're using the npm package, I'd recommend updating to version 1.4.0 to benefit from the most recent and accurate data.

To update, you can run:

```bash
npm install npm-malaysia-postcodes@1.4.0
```
Your feedback has been instrumental in improving the package, and I'm grateful for it. Please continue to share any discrepancies or suggestions you come across. Your collaboration is deeply valued!

Thank you for your ongoing support.
