### ISSUE TITLE
cannot use in angular cli version 16^

### ISSUE THREAD

**Issue by shahrul8k** [AsyrafHussin/npm-malaysia-postcodes#4]
cannot use in angular cli version 16^

error prompt:

Could not find a declaration file for module 'malaysia-postcodes'. 'c:/Users/v16/node_modules/malaysia-postcodes/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/malaysia-postcodes` if it exists or add a new declaration (.d.ts) file containing `declare module 'malaysia-postcodes';`ts(7016)
  
  
  
![error](https://github.com/AsyrafHussin/npm-malaysia-postcodes/assets/115688747/f20555ce-4db4-4398-a4f9-997cad6c611f)

**Comment by AsyrafHussin** [comment]
Hi @shahrul8k,

Thank you for bringing this to my attention.

I introduced TypeScript support in version 1.1.0. Please ensure you've updated to this version.
